{% set name = "vsgQt" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vsg-dev/vsgQt/archive/v{{ version }}.tar.gz
    sha256: 31756a513ec1e703296e5d256daaa0c8d49af7a1b605ff3fc9fbc902e5be1c8d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vsgqt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - pkgconfig  # [linux]
  host:
    - libgl-devel  # [linux]
    - libvulkan-headers
    - libvulkan-loader
    - qt
    - vsgXchange
    - vulkanscenegraph
  run:
    - libvulkan-loader
    - qt-main
    - vsgxchange
    - vulkanscenegraph

test:
  commands:
    - test -f $PREFIX/include/vsgQt/Export.h  # [not win]
    - test -f $PREFIX/lib/libvsgQt${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/cmake/vsgQt/vsgQtConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\vsgQt\\Export.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\vsgQt.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\vsgQt.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\vsgQt\\vsgQtConfig.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - libgl-devel  # [linux]
    - ninja  # [not win]
    - pkgconfig  # [linux]
    - vsgXchange
  files:
    - tests/

about:
  home: https://vsg-dev.github.io/vsg-dev.io/
  summary: Qt integration with VulkanSceneGraph
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/vsg-dev/vsgQt

extra:
  recipe-maintainers:
    - jeongseok-meta
